resolver: lts-14.27
allow-different-user: true

extra-deps:
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
- github: hamler-lang/CoreErlang
  commit: 2bacba611fed9eb773939964aa70e3ad49b8c816
- github: hamler-lang/purescript
  commit: 5c41feb6c3f0605238364020dafd1387f1b7eee0
- megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808
- github: hamler-lang/hamler
  commit: 39b407a6d147bd2f4d0bf494316129bae209dc93
- Glob-0.9.3
- ansi-terminal-0.8.2
- ansi-wl-pprint-0.6.8.2
- tasty-1.2

flags:
  these:
    assoc: false
    quickcheck: false

docker:
  repo: matsubara0507/stack-build
  env:
  - HAMLER_HOME=/usr/lib/hamler
  enable: true
